apiVersion: networking.example.com/v1alpha1
kind: ServiceRequest
metadata:
  name: myservice-request-app6
  namespace: ns1
spec:
  namespace: ns1
  vmName: testvm-app6
  services:
    - name: http
      targetPort: 8080
      port: 30007
    - name: ssh
      targetPort: 22
      port: 30004